import mods.jei.JEI;

JEI.hideCategory("appliedenergistics2.inscriber");
JEI.hideCategory("threng.energize");
JEI.hideCategory("threng.etch");
JEI.hideCategory("zmaster587.AR.lathe");
JEI.hideCategory("zmaster587.AR.sawMill");
JEI.hideCategory("zmaster587.AR.rollingMachine");
JEI.hideCategory("zmaster587.AR.chemicalReactor");
JEI.hideCategory("zmaster587.AR.crystallizer");
JEI.hideCategory("zmaster587.AR.electrolyzer");
JEI.hideCategory("zmaster587.AR.platePresser");
JEI.hideCategory("zmaster587.AR.centrifuge");
JEI.hideCategory("zmaster587.AR.precisionlaseretcher");
JEI.hideCategory("ore_leacher");
JEI.hideCategory("irradiator");
JEI.hideCategory("irradiator_fuel");
JEI.hideCategory("qmd.atmosphere_collector");
JEI.hideCategory("actuallyadditions.coffee");
JEI.hideCategory("actuallyadditions.compost");
JEI.hideCategory("actuallyadditions.crushing");
JEI.hideCategory("actuallyadditions.reconstructor");
JEI.hideCategory("actuallyadditions.empowerer");
JEI.hideCategory("nuclearcraft_decay_generator");
JEI.hideCategory("nuclearcraft_pebble_fission");
JEI.hideCategory("AlloySmelter");
JEI.hideCategory("ZombieGenerator");